import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Game from "../components/Game/Game";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>League Icon Guess</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.gameHeader}>
        <div></div>
        <div className={styles.gameTitle}>LoL Icon Guess</div>
        <div></div>
      </header>

      <main className={styles.main}>
        <Game></Game>
      </main>
    </div>
  );
}
